---
- name: Deploy blue cluster and RDS
  hosts: servers
  # connection: local #Connection tells there isnt any need for SSH
  gather_facts: False # Gather useful variables about remote hosts that can be used in playbooks
  become: no # Not seting as Root
  vars_files:
    - "../../group_vars/all_vars.yaml"

  tasks:
    - name: Deploy Blue Cluster
      shell: |
        cd "{{ blue_eks_dir }}"
        terraform apply -auto-approve

    - name: Deploy blue route for Route53
      shell: |
        cd "{{ blue_route53_dir }}"
        terraform apply -var weighted_blue=100 -auto-approve
