---
- name: Simulate a Canary Deployment
  hosts: servers
  # connection: local #Connection tells there isnt any need for SSH
  gather_facts: False # Gather useful variables about remote hosts that can be used in playbooks
  become: no # Not seting as Root
  vars_files:
    - "../../group_vars/all_vars.yaml"

  tasks:
###################### Deploy RDS ###################################
    - name: Deploy RDS 
      community.general.terraform:
        project_path: '{{ rds_dir }}'
        state: present

########### Deploy - [ blue=100% :: green=0% ] ######################
    - name: Deploy Blue cluster with route for Route53 with 100% of Traffic
      shell: |
        cd "{{ blue_dir }}"
        terraform apply -var weighted_percentage=100 -auto-approve

    - name: Deploy Green cluster with route for Route53 with 0% of Traffic
      shell: |
        cd "{{ green_dir }}"
        terraform apply -var weighted_percentage=0 -auto-approve

    - name: Host machine sleeps for 3 minutes for Testing and verfification
      shell: |
        sleep {{ testing_time_interval }}

########### Switch 1 - [ blue=90% :: green=10% ] ######################
    - name: Change Green cluster traffic weight to 10%
      shell: |
        cd "{{ green_dir }}"
        terraform apply -var weighted_percentage=10 -auto-approve
        
    - name: Change Blue cluster traffic weight to 90%
      shell: |
        cd "{{ blue_dir }}"
        terraform apply -var weighted_percentage=90 -auto-approve

    - name: Host machine sleeps for 3 minutes for Testing and verfification
      shell: |
        sleep {{ testing_time_interval }}

########### Switch 2 - [ blue=50% :: green=50% ] ######################
    - name: Change Green cluster traffic weight to 50%
      shell: |
        cd "{{ green_dir }}"
        terraform apply -var weighted_percentage=50 -auto-approve
        
    - name: Change Blue cluster traffic weight to 50%
      shell: |
        cd "{{ blue_dir }}"
        terraform apply -var weighted_percentage=50 -auto-approve

    - name: Host machine sleeps for 3 minutes for Testing and verfification
      shell: |
        sleep {{ testing_time_interval }}

########### Switch 3 - [ blue=0% :: green=100% ] ######################
    - name: Change Green cluster traffic weight to 100%
      shell: |
        cd "{{ green_dir }}"
        terraform apply -var weighted_percentage=100 -auto-approve
        
    - name: Change Blue cluster traffic weight to 0%
      shell: |
        cd "{{ blue_dir }}"
        terraform apply -var weighted_percentage=0 -auto-approve

    - name: Host machine sleeps for 3 minutes for Testing and verfification
      shell: |
        sleep {{ testing_time_interval }}

######################### Clean up ####################################
    
    - name: Use Terraform to destroy blue cluster
      shell: |
        cd "{{ blue_dir }}"
        terraform destroy -auto-approve
    
    - name: Use Terraform to destroy Green cluster
      shell: |
        cd "{{ green_dir }}"
        terraform destroy -auto-approve

    - name: Use Terraform to destroy RDS
      shell: |
        cd "{{ rds_dir }}"
        terraform destroy -auto-approve