---
- name: Deploy green cluster
  hosts: servers
  # connection: local #Connection tells there isnt any need for SSH
  gather_facts: False # Gather useful variables about remote hosts that can be used in playbooks
  become: no # Not seting as Root
  vars_files:
    - "../../group_vars/all_vars.yaml"

  tasks:
    - name: Deploy Green Cluster
      shell: |
        cd "{{ green_dir }}"
        terraform apply -var weighted_percentage=0 -auto-approve

      